%% SWE, Depth and Bulk Density Box Plots (Fig. 4);
%% 2022 & 2023;
figure;
hold on;

% Define sites for easier iteration
sites = {'Upper_Plateau', 'TVC', 'Valley', 'Small_Shrub', 'Mixed Shrub', 'Shrub Tree', 'Havikpak'};

% Define 3 grayscale colors
colors = {[0.2, 0.2, 0.2], [0.5, 0.5, 0.5], [0.7, 0.7, 0.7]};

blue_2022 = [0, 0, 0.8];  % Darker blue
blue_2023 = [0.4, 0.6, 1];  % Lighter blue

red_2022 = [0.8, 0, 0];  % Darker red
red_2023 = [1, 0.4, 0.4];  % Lighter red

% Use grayscale colors from provided list
gray_2022 = colors{1};  % Darker gray
gray_2023 = colors{2};  % Medium gray

% Positions for vertical lines
line_positions = [0.6, 1.2, 1.8, 2.4, 3.0, 3.6];

subplot(3,1,1);

% Plot for Upper Plateau
errorbar(0.1, Upper_Plateau.stats_2022_SD_D.Median, ...
    Upper_Plateau.stats_2022_SD_D.Median - Upper_Plateau.stats_2022_SD_D.IQR_25, ...
    Upper_Plateau.stats_2022_SD_D.IQR_75 - Upper_Plateau.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.12, Upper_Plateau.stats_2023_SD_D.Median, ...
    Upper_Plateau.stats_2023_SD_D.Median - Upper_Plateau.stats_2023_SD_D.IQR_25, ...
    Upper_Plateau.stats_2023_SD_D.IQR_75 - Upper_Plateau.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.2, Upper_Plateau.stats_2022_SD_A.Median, ...
    Upper_Plateau.stats_2022_SD_A.Median - Upper_Plateau.stats_2022_SD_A.IQR_25, ...
    Upper_Plateau.stats_2022_SD_A.IQR_75 - Upper_Plateau.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.22, Upper_Plateau.stats_2023_SD_A.Median, ...
    Upper_Plateau.stats_2023_SD_A.Median - Upper_Plateau.stats_2023_SD_A.IQR_25, ...
    Upper_Plateau.stats_2023_SD_A.IQR_75 - Upper_Plateau.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5, 'LineStyle', '--');

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.4, Magnaprobe_IQR_2022.Magnaprobe_UP.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_UP.Median - Magnaprobe_IQR_2022.Magnaprobe_UP.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_UP.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_UP.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(0.42, Magnaprobe_IQR_2023.Magnaprobe_UP.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_UP.Median - Magnaprobe_IQR_2023.Magnaprobe_UP.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_UP.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_UP.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5, 'LineStyle', '--');

%     d2.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.3, iqrResults_Pits.UpperPlateau.Median, ...
    iqrResults_Pits.UpperPlateau.Median - iqrResults_Pits.UpperPlateau.IQR_25, ...
    iqrResults_Pits.UpperPlateau.IQR_75 - iqrResults_Pits.UpperPlateau.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d3 = errorbar(0.32, iqrResults_SD_2023.Upper_Plateau.Median, ...
    iqrResults_SD_2023.Upper_Plateau.Median - iqrResults_SD_2023.Upper_Plateau.IQR_25, ...
    iqrResults_SD_2023.Upper_Plateau.IQR_75 - iqrResults_SD_2023.Upper_Plateau.Median, ...
    '+', 'Color', colors{2}, 'MarkerSize', 8, 'LineWidth', 2.5, 'LineStyle', '--');

%  d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for TVC
errorbar(0.7, TVC.stats_2022_SD_D.Median, ...
    TVC.stats_2022_SD_D.Median - TVC.stats_2022_SD_D.IQR_25, ...
    TVC.stats_2022_SD_D.IQR_75 - TVC.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.72, TVC.stats_2023_SD_D.Median, ...
    TVC.stats_2023_SD_D.Median - TVC.stats_2023_SD_D.IQR_25, ...
    TVC.stats_2023_SD_D.IQR_75 - TVC.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.8, TVC.stats_2022_SD_A.Median, ...
    TVC.stats_2022_SD_A.Median - TVC.stats_2022_SD_A.IQR_25, ...
    TVC.stats_2022_SD_A.IQR_75 - TVC.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.82, TVC.stats_2023_SD_A.Median, ...
    TVC.stats_2023_SD_A.Median - TVC.stats_2023_SD_A.IQR_25, ...
    TVC.stats_2023_SD_A.IQR_75 - TVC.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.0, Magnaprobe_IQR_2022.Magnaprobe_TVC.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_TVC.Median - Magnaprobe_IQR_2022.Magnaprobe_TVC.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_TVC.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_TVC.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(1.02, Magnaprobe_IQR_2023.Magnaprobe_TVC.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_TVC.Median - Magnaprobe_IQR_2023.Magnaprobe_TVC.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_TVC.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_TVC.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.9, iqrResults_Pits.TVC.Median, ...
    iqrResults_Pits.TVC.Median - iqrResults_Pits.TVC.IQR_25, ...
    iqrResults_Pits.TVC.IQR_75 - iqrResults_Pits.TVC.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d3 = errorbar(0.92, iqrResults_SD_2023.TVC.Median, ...
    iqrResults_SD_2023.TVC.Median - iqrResults_SD_2023.TVC.IQR_25, ...
    iqrResults_SD_2023.TVC.IQR_75 - iqrResults_SD_2023.TVC.Median, ...
    '+', 'Color', colors{2},  'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Valley
errorbar(1.3, Valley.stats_2022_SD_D.Median, ...
    Valley.stats_2022_SD_D.Median - Valley.stats_2022_SD_D.IQR_25, ...
    Valley.stats_2022_SD_D.IQR_75 - Valley.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.32, Valley.stats_2023_SD_D.Median, ...
    Valley.stats_2023_SD_D.Median - Valley.stats_2023_SD_D.IQR_25, ...
    Valley.stats_2023_SD_D.IQR_75 - Valley.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.4, Valley.stats_2022_SD_A.Median, ...
    Valley.stats_2022_SD_A.Median - Valley.stats_2022_SD_A.IQR_25, ...
    Valley.stats_2022_SD_A.IQR_75 - Valley.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(1.42, Valley.stats_2023_SD_A.Median, ...
    Valley.stats_2023_SD_A.Median - Valley.stats_2023_SD_A.IQR_25, ...
    Valley.stats_2023_SD_A.IQR_75 - Valley.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.6, Magnaprobe_IQR_2022.Magnaprobe_V.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_V.Median - Magnaprobe_IQR_2022.Magnaprobe_V.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_V.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_V.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(1.62, Magnaprobe_IQR_2023.Magnaprobe_V.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_V.Median - Magnaprobe_IQR_2023.Magnaprobe_V.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_V.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_V.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.5, iqrResults_Pits.Valley.Median, ...
    iqrResults_Pits.Valley.Median - iqrResults_Pits.Valley.IQR_25, ...
    iqrResults_Pits.Valley.IQR_75 - iqrResults_Pits.Valley.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d3 = errorbar(1.52, iqrResults_SD_2023.Valley.Median, ...
    iqrResults_SD_2023.Valley.Median - iqrResults_SD_2023.Valley.IQR_25, ...
    iqrResults_SD_2023.Valley.IQR_75 - iqrResults_SD_2023.Valley.Median, ...
    '+', 'Color', colors{2},  'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Small Shrub
errorbar(1.9, Small_Shrub.stats_2022_SD_D.Median, ...
    Small_Shrub.stats_2022_SD_D.Median - Small_Shrub.stats_2022_SD_D.IQR_25, ...
    Small_Shrub.stats_2022_SD_D.IQR_75 - Small_Shrub.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.92, Small_Shrub.stats_2023_SD_D.Median, ...
    Small_Shrub.stats_2023_SD_D.Median - Small_Shrub.stats_2023_SD_D.IQR_25, ...
    Small_Shrub.stats_2023_SD_D.IQR_75 - Small_Shrub.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.0, Small_Shrub.stats_2022_SD_A.Median, ...
    Small_Shrub.stats_2022_SD_A.Median - Small_Shrub.stats_2022_SD_A.IQR_25, ...
    Small_Shrub.stats_2022_SD_A.IQR_75 - Small_Shrub.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.02, Small_Shrub.stats_2023_SD_A.Median, ...
    Small_Shrub.stats_2023_SD_A.Median - Small_Shrub.stats_2023_SD_A.IQR_25, ...
    Small_Shrub.stats_2023_SD_A.IQR_75 - Small_Shrub.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.2, Magnaprobe_IQR_2022.Magnaprobe_SS.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_SS.Median - Magnaprobe_IQR_2022.Magnaprobe_SS.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_SS.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_SS.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(2.22, Magnaprobe_IQR_2023.Magnaprobe_SS.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_SS.Median - Magnaprobe_IQR_2023.Magnaprobe_SS.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_SS.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_SS.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.1, iqrResults_Pits.SmallShrub.Median, ...
    iqrResults_Pits.SmallShrub.Median - iqrResults_Pits.SmallShrub.IQR_25, ...
    iqrResults_Pits.SmallShrub.IQR_75 - iqrResults_Pits.SmallShrub.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d3 = errorbar(2.12, iqrResults_SD_2023.Small_Shrub.Median, ...
    iqrResults_SD_2023.Small_Shrub.Median - iqrResults_SD_2023.Small_Shrub.IQR_25, ...
    iqrResults_SD_2023.Small_Shrub.IQR_75 - iqrResults_SD_2023.Small_Shrub.Median, ...
    '+', 'Color', colors{2},  'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Mixed Shrub
errorbar(2.5, Mixed_Shrub.stats_2022_SD_D.Median, ...
    Mixed_Shrub.stats_2022_SD_D.Median - Mixed_Shrub.stats_2022_SD_D.IQR_25, ...
    Mixed_Shrub.stats_2022_SD_D.IQR_75 - Mixed_Shrub.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(2.52, Mixed_Shrub.stats_2023_SD_D.Median, ...
    Mixed_Shrub.stats_2023_SD_D.Median - Mixed_Shrub.stats_2023_SD_D.IQR_25, ...
    Mixed_Shrub.stats_2023_SD_D.IQR_75 - Mixed_Shrub.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.6, Mixed_Shrub.stats_2022_SD_A.Median, ...
    Mixed_Shrub.stats_2022_SD_A.Median - Mixed_Shrub.stats_2022_SD_A.IQR_25, ...
    Mixed_Shrub.stats_2022_SD_A.IQR_75 - Mixed_Shrub.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.62, Mixed_Shrub.stats_2023_SD_A.Median, ...
    Mixed_Shrub.stats_2023_SD_A.Median - Mixed_Shrub.stats_2023_SD_A.IQR_25, ...
    Mixed_Shrub.stats_2023_SD_A.IQR_75 - Mixed_Shrub.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.8, Magnaprobe_IQR_2022.Magnaprobe_MS.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_MS.Median - Magnaprobe_IQR_2022.Magnaprobe_MS.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_MS.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_MS.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(2.82, Magnaprobe_IQR_2023.Magnaprobe_MS.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_MS.Median - Magnaprobe_IQR_2023.Magnaprobe_MS.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_MS.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_MS.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

errorbar(2.7, iqrResults_Pits.MixedShrub.Median, ...
    iqrResults_Pits.MixedShrub.Median - iqrResults_Pits.MixedShrub.IQR_25, ...
    iqrResults_Pits.MixedShrub.IQR_75 - iqrResults_Pits.MixedShrub.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d3 = errorbar(2.72, iqrResults_SD_2023.Mixed_Shrub.Median, ...
    iqrResults_SD_2023.Mixed_Shrub.Median - iqrResults_SD_2023.Mixed_Shrub.IQR_25, ...
    iqrResults_SD_2023.Mixed_Shrub.IQR_75 - iqrResults_SD_2023.Mixed_Shrub.Median, ...
    '+', 'Color', colors{2}, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Shrub Tree
h1 = errorbar(3.1, Shrub_Tree.stats_2022_SD_D.Median, ...
    Shrub_Tree.stats_2022_SD_D.Median - Shrub_Tree.stats_2022_SD_D.IQR_25, ...
    Shrub_Tree.stats_2022_SD_D.IQR_75 - Shrub_Tree.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.12, Shrub_Tree.stats_2023_SD_D.Median, ...
    Shrub_Tree.stats_2023_SD_D.Median - Shrub_Tree.stats_2023_SD_D.IQR_25, ...
    Shrub_Tree.stats_2023_SD_D.IQR_75 - Shrub_Tree.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

h2 = errorbar(3.2, Shrub_Tree.stats_2022_SD_A.Median, ...
    Shrub_Tree.stats_2022_SD_A.Median - Shrub_Tree.stats_2022_SD_A.IQR_25, ...
    Shrub_Tree.stats_2022_SD_A.IQR_75 - Shrub_Tree.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.22, Shrub_Tree.stats_2023_SD_A.Median, ...
    Shrub_Tree.stats_2023_SD_A.Median - Shrub_Tree.stats_2023_SD_A.IQR_25, ...
    Shrub_Tree.stats_2023_SD_A.IQR_75 - Shrub_Tree.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

h3 = errorbar(3.4, Magnaprobe_IQR_2022.Magnaprobe_TS.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_TS.Median - Magnaprobe_IQR_2022.Magnaprobe_TS.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_TS.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_TS.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(3.42, Magnaprobe_IQR_2023.Magnaprobe_TS.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_TS.Median - Magnaprobe_IQR_2023.Magnaprobe_TS.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_TS.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_TS.Median, ...
    'o', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

h4 = errorbar(3.3, iqrResults_Pits.ShrubTree.Median, ...
    iqrResults_Pits.ShrubTree.Median - iqrResults_Pits.ShrubTree.IQR_25, ...
    iqrResults_Pits.ShrubTree.IQR_75 - iqrResults_Pits.ShrubTree.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d3 = errorbar(3.32, iqrResults_SD_2023.Shrub_Tree.Median, ...
    iqrResults_SD_2023.Shrub_Tree.Median - iqrResults_SD_2023.Shrub_Tree.IQR_25, ...
    iqrResults_SD_2023.Shrub_Tree.IQR_75 - iqrResults_SD_2023.Shrub_Tree.Median, ...
    '+', 'Color', colors{2},  'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on;

% Plot for Havikpak
errorbar(3.7, Havikpak.stats_2022_SD_D.Median, ...
    Havikpak.stats_2022_SD_D.Median - Havikpak.stats_2022_SD_D.IQR_25, ...
    Havikpak.stats_2022_SD_D.IQR_75 - Havikpak.stats_2022_SD_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.72, Havikpak.stats_2023_SD_D.Median, ...
    Havikpak.stats_2023_SD_D.Median - Havikpak.stats_2023_SD_D.IQR_25, ...
    Havikpak.stats_2023_SD_D.IQR_75 - Havikpak.stats_2023_SD_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.8, Havikpak.stats_2022_SD_A.Median, ...
    Havikpak.stats_2022_SD_A.Median - Havikpak.stats_2022_SD_A.IQR_75, ...
    Havikpak.stats_2022_SD_A.IQR_75 - Havikpak.stats_2022_SD_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.82, Havikpak.stats_2023_SD_A.Median, ...
    Havikpak.stats_2023_SD_A.Median - Havikpak.stats_2023_SD_A.IQR_75, ...
    Havikpak.stats_2023_SD_A.IQR_75 - Havikpak.stats_2023_SD_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(4.0, Magnaprobe_IQR_2022.Magnaprobe_H.Median, ...
    Magnaprobe_IQR_2022.Magnaprobe_H.Median - Magnaprobe_IQR_2022.Magnaprobe_H.IQR_25, ...
    Magnaprobe_IQR_2022.Magnaprobe_H.IQR_75 - Magnaprobe_IQR_2022.Magnaprobe_H.Median, ...
    'o', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(4.02, Magnaprobe_IQR_2023.Magnaprobe_H.Median, ...
    Magnaprobe_IQR_2023.Magnaprobe_H.Median - Magnaprobe_IQR_2023.Magnaprobe_H.IQR_25, ...
    Magnaprobe_IQR_2023.Magnaprobe_H.IQR_75 - Magnaprobe_IQR_2023.Magnaprobe_H.Median, ...
    'o', 'Color', gray_2023,  'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

errorbar(3.9, iqrResults_Pits.Havikpak.Median, ...
    iqrResults_Pits.Havikpak.Median - iqrResults_Pits.Havikpak.IQR_25, ...
    iqrResults_Pits.Havikpak.IQR_75 - iqrResults_Pits.Havikpak.Median, ...
    '+', 'Color', colors{1}, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d3 = errorbar(3.92, iqrResults_SD_2023.Havikpak.Median, ...
    iqrResults_SD_2023.Havikpak.Median - iqrResults_SD_2023.Havikpak.IQR_25, ...
    iqrResults_SD_2023.Havikpak.IQR_75 - iqrResults_SD_2023.Havikpak.Median, ...
    '+', 'Color', colors{2},  'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on;

% Add vertical dashed lines
for pos = line_positions
    xline(pos, 'k', 'LineWidth', 1);
end

% Set plot limits and labels
xlim([0 4.2]);
ylim([0 1]); 

xticks([0.3 0.9 1.5 2.1 2.7 3.3 3.9]);
xticklabels({'Upper Plateau','TVC','Valley','Small Shrub','Mixed Shrub','Shrub Tree','Havikpak'});

ylabel('Snow Depth (m)');
% legend('Default SVS2-Crocus', 'Arctic SVS2-Crocus', 'Magnaprobe', 'Pit', 'Location','best');
hold on; 

subplot(3,1,2);
% Plot for Upper Plateau
errorbar(0.1, Upper_Plateau.stats_2022_SWE_D.Median, ...
    Upper_Plateau.stats_2022_SWE_D.Median - Upper_Plateau.stats_2022_SWE_D.IQR_25, ...
    Upper_Plateau.stats_2022_SWE_D.IQR_75 - Upper_Plateau.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.12, Upper_Plateau.stats_2023_SWE_D.Median, ...
    Upper_Plateau.stats_2023_SWE_D.Median - Upper_Plateau.stats_2023_SWE_D.IQR_25, ...
    Upper_Plateau.stats_2023_SWE_D.IQR_75 - Upper_Plateau.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.2, Upper_Plateau.stats_2022_SWE_A.Median, ...
    Upper_Plateau.stats_2022_SWE_A.Median - Upper_Plateau.stats_2022_SWE_A.IQR_25, ...
    Upper_Plateau.stats_2022_SWE_A.IQR_75 - Upper_Plateau.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.22, Upper_Plateau.stats_2023_SWE_A.Median, ...
    Upper_Plateau.stats_2023_SWE_A.Median - Upper_Plateau.stats_2023_SWE_A.IQR_25, ...
    Upper_Plateau.stats_2023_SWE_A.IQR_75 - Upper_Plateau.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.3, iqrResults_SWE_2022.Upper_Plateau.Median, ...
    iqrResults_SWE_2022.Upper_Plateau.Median - iqrResults_SWE_2022.Upper_Plateau.IQR_25, ...
    iqrResults_SWE_2022.Upper_Plateau.IQR_75 - iqrResults_SWE_2022.Upper_Plateau.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(0.32, iqrResults_SWE_2023.Upper_Plateau.Median, ...
    iqrResults_SWE_2023.Upper_Plateau.Median - iqrResults_SWE_2023.Upper_Plateau.IQR_25, ...
    iqrResults_SWE_2023.Upper_Plateau.IQR_75 - iqrResults_SWE_2023.Upper_Plateau.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

h5 = errorbar(0.5, iqrResults_SWE_Course.Upper_Plateau.Median, ...
    iqrResults_SWE_Course.Upper_Plateau.Median - iqrResults_SWE_Course.Upper_Plateau.IQR_25, ...
    iqrResults_SWE_Course.Upper_Plateau.IQR_75 - iqrResults_SWE_Course.Upper_Plateau.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     h2.Bar.LineStyle = 'dotted'

hold on; 

% Plot for TVC
errorbar(0.7, TVC.stats_2022_SWE_D.Median, ...
    TVC.stats_2022_SWE_D.Median - TVC.stats_2022_SWE_D.IQR_25, ...
    TVC.stats_2022_SWE_D.IQR_75 - TVC.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.72, TVC.stats_2023_SWE_D.Median, ...
    TVC.stats_2023_SWE_D.Median - TVC.stats_2023_SWE_D.IQR_25, ...
    TVC.stats_2023_SWE_D.IQR_75 - TVC.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.8, TVC.stats_2022_SWE_A.Median, ...
    TVC.stats_2022_SWE_A.Median - TVC.stats_2022_SWE_A.IQR_25, ...
    TVC.stats_2022_SWE_A.IQR_75 - TVC.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.82, TVC.stats_2023_SWE_A.Median, ...
    TVC.stats_2023_SWE_A.Median - TVC.stats_2023_SWE_A.IQR_25, ...
    TVC.stats_2023_SWE_A.IQR_75 - TVC.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.9, iqrResults_SWE_2022.TVC.Median, ...
    iqrResults_SWE_2022.TVC.Median - iqrResults_SWE_2022.TVC.IQR_25, ...
    iqrResults_SWE_2022.TVC.IQR_75 - iqrResults_SWE_2022.TVC.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(0.92, iqrResults_SWE_2023.TVC.Median, ...
    iqrResults_SWE_2023.TVC.Median - iqrResults_SWE_2023.TVC.IQR_25, ...
    iqrResults_SWE_2023.TVC.IQR_75 - iqrResults_SWE_2023.TVC.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(1.1, iqrResults_SWE_Course.TVC.Median, ...
    iqrResults_SWE_Course.TVC.Median - iqrResults_SWE_Course.TVC.IQR_25, ...
    iqrResults_SWE_Course.TVC.IQR_75 - iqrResults_SWE_Course.TVC.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Valley
errorbar(1.3, Valley.stats_2022_SWE_D.Median, ...
    Valley.stats_2022_SWE_D.Median - Valley.stats_2022_SWE_D.IQR_25, ...
    Valley.stats_2022_SWE_D.IQR_75 - Valley.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.32, Valley.stats_2023_SWE_D.Median, ...
    Valley.stats_2023_SWE_D.Median - Valley.stats_2023_SWE_D.IQR_25, ...
    Valley.stats_2023_SWE_D.IQR_75 - Valley.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.4, Valley.stats_2022_SWE_A.Median, ...
    Valley.stats_2022_SWE_A.Median - Valley.stats_2022_SWE_A.IQR_25, ...
    Valley.stats_2022_SWE_A.IQR_75 - Valley.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(1.42, Valley.stats_2023_SWE_A.Median, ...
    Valley.stats_2023_SWE_A.Median - Valley.stats_2023_SWE_A.IQR_25, ...
    Valley.stats_2023_SWE_A.IQR_75 - Valley.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.5, iqrResults_SWE_2022.Valley.Median, ...
    iqrResults_SWE_2022.Valley.Median - iqrResults_SWE_2022.Valley.IQR_25, ...
    iqrResults_SWE_2022.Valley.IQR_75 - iqrResults_SWE_2022.Valley.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(1.52, iqrResults_SWE_2023.Valley.Median, ...
    iqrResults_SWE_2023.Valley.Median - iqrResults_SWE_2023.Valley.IQR_25, ...
    iqrResults_SWE_2023.Valley.IQR_75 - iqrResults_SWE_2023.Valley.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(1.7, iqrResults_SWE_Course.Valley.Median, ...
    iqrResults_SWE_Course.Valley.Median - iqrResults_SWE_Course.Valley.IQR_25, ...
    iqrResults_SWE_Course.Valley.IQR_75 - iqrResults_SWE_Course.Valley.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Small Shrub
errorbar(1.9, Small_Shrub.stats_2022_SWE_D.Median, ...
    Small_Shrub.stats_2022_SWE_D.Median - Small_Shrub.stats_2022_SWE_D.IQR_25, ...
    Small_Shrub.stats_2022_SWE_D.IQR_75 - Small_Shrub.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.92, Small_Shrub.stats_2023_SWE_D.Median, ...
    Small_Shrub.stats_2023_SWE_D.Median - Small_Shrub.stats_2023_SWE_D.IQR_25, ...
    Small_Shrub.stats_2023_SWE_D.IQR_75 - Small_Shrub.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.0, Small_Shrub.stats_2022_SWE_A.Median, ...
    Small_Shrub.stats_2022_SWE_A.Median - Small_Shrub.stats_2022_SWE_A.IQR_25, ...
    Small_Shrub.stats_2022_SWE_A.IQR_75 - Small_Shrub.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.01, Small_Shrub.stats_2023_SWE_A.Median, ...
    Small_Shrub.stats_2023_SWE_A.Median - Small_Shrub.stats_2023_SWE_A.IQR_25, ...
    Small_Shrub.stats_2023_SWE_A.IQR_75 - Small_Shrub.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.1, iqrResults_SWE_2022.Small_Shrub.Median, ...
    iqrResults_SWE_2022.Small_Shrub.Median - iqrResults_SWE_2022.Small_Shrub.IQR_25, ...
    iqrResults_SWE_2022.Small_Shrub.IQR_75 - iqrResults_SWE_2022.Small_Shrub.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(2.12, iqrResults_SWE_2023.Small_Shrub.Median, ...
    iqrResults_SWE_2023.Small_Shrub.Median - iqrResults_SWE_2023.Small_Shrub.IQR_25, ...
    iqrResults_SWE_2023.Small_Shrub.IQR_75 - iqrResults_SWE_2023.Small_Shrub.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(2.3, iqrResults_SWE_Course.Small_Shrub.Median, ...
    iqrResults_SWE_Course.Small_Shrub.Median - iqrResults_SWE_Course.Small_Shrub.IQR_25, ...
    iqrResults_SWE_Course.Small_Shrub.IQR_75 - iqrResults_SWE_Course.Small_Shrub.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Mixed Shrub
errorbar(2.5, Mixed_Shrub.stats_2022_SWE_D.Median, ...
    Mixed_Shrub.stats_2022_SWE_D.Median - Mixed_Shrub.stats_2022_SWE_D.IQR_25, ...
    Mixed_Shrub.stats_2022_SWE_D.IQR_75 - Mixed_Shrub.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(2.52, Mixed_Shrub.stats_2023_SWE_D.Median, ...
    Mixed_Shrub.stats_2023_SWE_D.Median - Mixed_Shrub.stats_2023_SWE_D.IQR_25, ...
    Mixed_Shrub.stats_2023_SWE_D.IQR_75 - Mixed_Shrub.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.6, Mixed_Shrub.stats_2022_SWE_A.Median, ...
    Mixed_Shrub.stats_2022_SWE_A.Median - Mixed_Shrub.stats_2022_SWE_A.IQR_25, ...
    Mixed_Shrub.stats_2022_SWE_A.IQR_75 - Mixed_Shrub.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.62, Mixed_Shrub.stats_2023_SWE_A.Median, ...
    Mixed_Shrub.stats_2023_SWE_A.Median - Mixed_Shrub.stats_2023_SWE_A.IQR_25, ...
    Mixed_Shrub.stats_2023_SWE_A.IQR_75 - Mixed_Shrub.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'
    
hold on; 

errorbar(2.7, iqrResults_SWE_2022.Mixed_Shrub.Median, ...
    iqrResults_SWE_2022.Mixed_Shrub.Median - iqrResults_SWE_2022.Mixed_Shrub.IQR_25, ...
    iqrResults_SWE_2022.Mixed_Shrub.IQR_75 - iqrResults_SWE_2022.Mixed_Shrub.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(2.72, iqrResults_SWE_2023.Mixed_Shrub.Median, ...
    iqrResults_SWE_2023.Mixed_Shrub.Median - iqrResults_SWE_2023.Mixed_Shrub.IQR_25, ...
    iqrResults_SWE_2023.Mixed_Shrub.IQR_75 - iqrResults_SWE_2023.Mixed_Shrub.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(2.9, iqrResults_SWE_Course.Mixed_Shrub.Median, ...
    iqrResults_SWE_Course.Mixed_Shrub.Median - iqrResults_SWE_Course.Mixed_Shrub.IQR_25, ...
    iqrResults_SWE_Course.Mixed_Shrub.IQR_75 - iqrResults_SWE_Course.Mixed_Shrub.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Shrub Tree
errorbar(3.1, Shrub_Tree.stats_2022_SWE_D.Median, ...
    Shrub_Tree.stats_2022_SWE_D.Median - Shrub_Tree.stats_2022_SWE_D.IQR_25, ...
    Shrub_Tree.stats_2022_SWE_D.IQR_75 - Shrub_Tree.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.12, Shrub_Tree.stats_2023_SWE_D.Median, ...
    Shrub_Tree.stats_2023_SWE_D.Median - Shrub_Tree.stats_2023_SWE_D.IQR_25, ...
    Shrub_Tree.stats_2023_SWE_D.IQR_75 - Shrub_Tree.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.2, Shrub_Tree.stats_2022_SWE_A.Median, ...
    Shrub_Tree.stats_2022_SWE_A.Median - Shrub_Tree.stats_2022_SWE_A.IQR_25, ...
    Shrub_Tree.stats_2022_SWE_A.IQR_75 - Shrub_Tree.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.22, Shrub_Tree.stats_2023_SWE_A.Median, ...
    Shrub_Tree.stats_2023_SWE_A.Median - Shrub_Tree.stats_2023_SWE_A.IQR_25, ...
    Shrub_Tree.stats_2023_SWE_A.IQR_75 - Shrub_Tree.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.3, iqrResults_SWE_2022.Shrub_Tree.Median, ...
    iqrResults_SWE_2022.Shrub_Tree.Median - iqrResults_SWE_2022.Shrub_Tree.IQR_25, ...
    iqrResults_SWE_2022.Shrub_Tree.IQR_75 - iqrResults_SWE_2022.Shrub_Tree.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(3.32, iqrResults_SWE_2023.Shrub_Tree.Median, ...
    iqrResults_SWE_2023.Shrub_Tree.Median - iqrResults_SWE_2023.Shrub_Tree.IQR_25, ...
    iqrResults_SWE_2023.Shrub_Tree.IQR_75 - iqrResults_SWE_2023.Shrub_Tree.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(3.5, iqrResults_SWE_Course.Shrub_Tree.Median, ...
    iqrResults_SWE_Course.Shrub_Tree.Median - iqrResults_SWE_Course.Shrub_Tree.IQR_25, ...
    iqrResults_SWE_Course.Shrub_Tree.IQR_75 - iqrResults_SWE_Course.Shrub_Tree.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Havikpak
errorbar(3.7, Havikpak.stats_2022_SWE_D.Median, ...
    Havikpak.stats_2022_SWE_D.Median - Havikpak.stats_2022_SWE_D.IQR_25, ...
    Havikpak.stats_2022_SWE_D.IQR_75 - Havikpak.stats_2022_SWE_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.72, Havikpak.stats_2023_SWE_D.Median, ...
    Havikpak.stats_2023_SWE_D.Median - Havikpak.stats_2023_SWE_D.IQR_25, ...
    Havikpak.stats_2023_SWE_D.IQR_75 - Havikpak.stats_2023_SWE_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.8, Havikpak.stats_2022_SWE_A.Median, ...
    Havikpak.stats_2022_SWE_A.Median - Havikpak.stats_2022_SWE_A.IQR_75, ...
    Havikpak.stats_2022_SWE_A.IQR_75 - Havikpak.stats_2022_SWE_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.82, Havikpak.stats_2023_SWE_A.Median, ...
    Havikpak.stats_2023_SWE_A.Median - Havikpak.stats_2023_SWE_A.IQR_75, ...
    Havikpak.stats_2023_SWE_A.IQR_75 - Havikpak.stats_2023_SWE_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.9, iqrResults_SWE_2022.Havikpak.Median, ...
    iqrResults_SWE_2022.Havikpak.Median - iqrResults_SWE_2022.Havikpak.IQR_25, ...
    iqrResults_SWE_2022.Havikpak.IQR_75 - iqrResults_SWE_2022.Havikpak.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(3.92, iqrResults_SWE_2023.Havikpak.Median, ...
    iqrResults_SWE_2023.Havikpak.Median - iqrResults_SWE_2023.Havikpak.IQR_25, ...
    iqrResults_SWE_2023.Havikpak.IQR_75 - iqrResults_SWE_2023.Havikpak.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

d3 = errorbar(4.1, iqrResults_SWE_Course.Havikpak.Median, ...
    iqrResults_SWE_Course.Havikpak.Median - iqrResults_SWE_Course.Havikpak.IQR_25, ...
    iqrResults_SWE_Course.Havikpak.IQR_75 - iqrResults_SWE_Course.Havikpak.Median, ...
    '*', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d3.Bar.LineStyle = 'dotted'

hold on; 

% Add vertical dashed lines
for pos = line_positions
    xline(pos, 'k', 'LineWidth', 1);
end

% Set plot limits and labels
xlim([0 4.2]);
ylim([0 200]); 

xticks([0.3 0.9 1.5 2.1 2.7 3.3 3.9]);
xticklabels({'Upper Plateau','TVC','Valley','Small Shrub','Mixed Shrub','Shrub Tree','Havikpak'});

legend([h1, h2, h3, h4, h5], {'Default SVS2-Crocus', 'Arctic SVS2-Crocus', 'Magnaprobe', 'Pit', 'SWE Tube'}, 'Position', [0.5, 0.05, 0.1, 0.1]);
hold on; 

ylabel('SWE (mm)');
hold on; 

subplot(3,1,3);
% Plot for Upper Plateau
errorbar(0.1, Upper_Plateau.stats_2022_Density_D.Median, ...
    Upper_Plateau.stats_2022_Density_D.Median - Upper_Plateau.stats_2022_Density_D.IQR_25, ...
    Upper_Plateau.stats_2022_Density_D.IQR_75 - Upper_Plateau.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.12, Upper_Plateau.stats_2023_Density_D.Median, ...
    Upper_Plateau.stats_2023_Density_D.Median - Upper_Plateau.stats_2023_Density_D.IQR_25, ...
    Upper_Plateau.stats_2023_Density_D.IQR_75 - Upper_Plateau.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.2, Upper_Plateau.stats_2022_Density_A.Median, ...
    Upper_Plateau.stats_2022_Density_A.Median - Upper_Plateau.stats_2022_Density_A.IQR_25, ...
    Upper_Plateau.stats_2022_Density_A.IQR_75 - Upper_Plateau.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.22, Upper_Plateau.stats_2023_Density_A.Median, ...
    Upper_Plateau.stats_2023_Density_A.Median - Upper_Plateau.stats_2023_Density_A.IQR_25, ...
    Upper_Plateau.stats_2023_Density_A.IQR_75 - Upper_Plateau.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.3, iqrResults_BD_2022.Upper_Plateau.Median, ...
    iqrResults_BD_2022.Upper_Plateau.Median - iqrResults_BD_2022.Upper_Plateau.IQR_25, ...
    iqrResults_BD_2022.Upper_Plateau.IQR_75 - iqrResults_BD_2022.Upper_Plateau.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(0.32, iqrResults_BD_2023.Upper_Plateau.Median, ...
    iqrResults_BD_2023.Upper_Plateau.Median - iqrResults_BD_2023.Upper_Plateau.IQR_25, ...
    iqrResults_BD_2023.Upper_Plateau.IQR_75 - iqrResults_BD_2023.Upper_Plateau.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

% Plot for TVC
errorbar(0.7, TVC.stats_2022_Density_D.Median, ...
    TVC.stats_2022_Density_D.Median - TVC.stats_2022_Density_D.IQR_25, ...
    TVC.stats_2022_Density_D.IQR_75 - TVC.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(0.72, TVC.stats_2023_Density_D.Median, ...
    TVC.stats_2023_Density_D.Median - TVC.stats_2023_Density_D.IQR_25, ...
    TVC.stats_2023_Density_D.IQR_75 - TVC.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.8, TVC.stats_2022_Density_A.Median, ...
    TVC.stats_2022_Density_A.Median - TVC.stats_2022_Density_A.IQR_25, ...
    TVC.stats_2022_Density_A.IQR_75 - TVC.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(0.82, TVC.stats_2023_Density_A.Median, ...
    TVC.stats_2023_Density_A.Median - TVC.stats_2023_Density_A.IQR_25, ...
    TVC.stats_2023_Density_A.IQR_75 - TVC.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(0.9, iqrResults_BD_2022.TVC.Median, ...
    iqrResults_BD_2022.TVC.Median - iqrResults_BD_2022.TVC.IQR_25, ...
    iqrResults_BD_2022.TVC.IQR_75 - iqrResults_BD_2022.TVC.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(0.92, iqrResults_BD_2023.TVC.Median, ...
    iqrResults_BD_2023.TVC.Median - iqrResults_BD_2023.TVC.IQR_25, ...
    iqrResults_BD_2023.TVC.IQR_75 - iqrResults_BD_2023.TVC.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Valley
errorbar(1.3, Valley.stats_2022_Density_D.Median, ...
    Valley.stats_2022_Density_D.Median - Valley.stats_2022_Density_D.IQR_25, ...
    Valley.stats_2022_Density_D.IQR_75 - Valley.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.32, Valley.stats_2023_Density_D.Median, ...
    Valley.stats_2023_Density_D.Median - Valley.stats_2023_Density_D.IQR_25, ...
    Valley.stats_2023_Density_D.IQR_75 - Valley.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.4, Valley.stats_2022_Density_A.Median, ...
    Valley.stats_2022_Density_A.Median - Valley.stats_2022_Density_A.IQR_25, ...
    Valley.stats_2022_Density_A.IQR_75 - Valley.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(1.42, Valley.stats_2023_Density_A.Median, ...
    Valley.stats_2023_Density_A.Median - Valley.stats_2023_Density_A.IQR_25, ...
    Valley.stats_2023_Density_A.IQR_75 - Valley.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(1.5, iqrResults_BD_2022.Valley.Median, ...
    iqrResults_BD_2022.Valley.Median - iqrResults_BD_2022.Valley.IQR_25, ...
    iqrResults_BD_2022.Valley.IQR_75 - iqrResults_BD_2022.Valley.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(1.52, iqrResults_BD_2023.Valley.Median, ...
    iqrResults_BD_2023.Valley.Median - iqrResults_BD_2023.Valley.IQR_25, ...
    iqrResults_BD_2023.Valley.IQR_75 - iqrResults_BD_2023.Valley.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Small Shrub
errorbar(1.9, Small_Shrub.stats_2022_Density_D.Median, ...
    Small_Shrub.stats_2022_Density_D.Median - Small_Shrub.stats_2022_Density_D.IQR_25, ...
    Small_Shrub.stats_2022_Density_D.IQR_75 - Small_Shrub.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(1.92, Small_Shrub.stats_2023_Density_D.Median, ...
    Small_Shrub.stats_2023_Density_D.Median - Small_Shrub.stats_2023_Density_D.IQR_25, ...
    Small_Shrub.stats_2023_Density_D.IQR_75 - Small_Shrub.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on;

errorbar(2.0, Small_Shrub.stats_2022_Density_A.Median, ...
    Small_Shrub.stats_2022_Density_A.Median - Small_Shrub.stats_2022_Density_A.IQR_25, ...
    Small_Shrub.stats_2022_Density_A.IQR_75 - Small_Shrub.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.02, Small_Shrub.stats_2023_Density_A.Median, ...
    Small_Shrub.stats_2023_Density_A.Median - Small_Shrub.stats_2023_Density_A.IQR_25, ...
    Small_Shrub.stats_2023_Density_A.IQR_75 - Small_Shrub.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.1, iqrResults_BD_2022.Small_Shrub.Median, ...
    iqrResults_BD_2022.Small_Shrub.Median - iqrResults_BD_2022.Small_Shrub.IQR_25, ...
    iqrResults_BD_2022.Small_Shrub.IQR_75 - iqrResults_BD_2022.Small_Shrub.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d2 = errorbar(2.12, iqrResults_BD_2023.Small_Shrub.Median, ...
    iqrResults_BD_2023.Small_Shrub.Median - iqrResults_BD_2023.Small_Shrub.IQR_25, ...
    iqrResults_BD_2023.Small_Shrub.IQR_75 - iqrResults_BD_2023.Small_Shrub.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on; 

% Plot for Mixed Shrub
errorbar(2.5, Mixed_Shrub.stats_2022_Density_D.Median, ...
    Mixed_Shrub.stats_2022_Density_D.Median - Mixed_Shrub.stats_2022_Density_D.IQR_25, ...
    Mixed_Shrub.stats_2022_Density_D.IQR_75 - Mixed_Shrub.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(2.52, Mixed_Shrub.stats_2023_Density_D.Median, ...
    Mixed_Shrub.stats_2023_Density_D.Median - Mixed_Shrub.stats_2023_Density_D.IQR_25, ...
    Mixed_Shrub.stats_2023_Density_D.IQR_75 - Mixed_Shrub.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.6, Mixed_Shrub.stats_2022_Density_A.Median, ...
    Mixed_Shrub.stats_2022_Density_A.Median - Mixed_Shrub.stats_2022_Density_A.IQR_25, ...
    Mixed_Shrub.stats_2022_Density_A.IQR_75 - Mixed_Shrub.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(2.62, Mixed_Shrub.stats_2023_Density_A.Median, ...
    Mixed_Shrub.stats_2023_Density_A.Median - Mixed_Shrub.stats_2023_Density_A.IQR_25, ...
    Mixed_Shrub.stats_2023_Density_A.IQR_75 - Mixed_Shrub.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(2.72, iqrResults_BD_2022.Mixed_Shrub.Median, ...
    iqrResults_BD_2022.Mixed_Shrub.Median - iqrResults_BD_2022.Mixed_Shrub.IQR_25, ...
    iqrResults_BD_2022.Mixed_Shrub.IQR_75 - iqrResults_BD_2022.Mixed_Shrub.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(2.7, iqrResults_BD_2023.Mixed_Shrub.Median, ...
    iqrResults_BD_2023.Mixed_Shrub.Median - iqrResults_BD_2023.Mixed_Shrub.IQR_25, ...
    iqrResults_BD_2023.Mixed_Shrub.IQR_75 - iqrResults_BD_2023.Mixed_Shrub.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

% Plot for Shrub Tree
errorbar(3.1, Shrub_Tree.stats_2022_Density_D.Median, ...
    Shrub_Tree.stats_2022_Density_D.Median - Shrub_Tree.stats_2022_Density_D.IQR_25, ...
    Shrub_Tree.stats_2022_Density_D.IQR_75 - Shrub_Tree.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.12, Shrub_Tree.stats_2023_Density_D.Median, ...
    Shrub_Tree.stats_2023_Density_D.Median - Shrub_Tree.stats_2023_Density_D.IQR_25, ...
    Shrub_Tree.stats_2023_Density_D.IQR_75 - Shrub_Tree.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.2, Shrub_Tree.stats_2022_Density_A.Median, ...
    Shrub_Tree.stats_2022_Density_A.Median - Shrub_Tree.stats_2022_Density_A.IQR_25, ...
    Shrub_Tree.stats_2022_Density_A.IQR_75 - Shrub_Tree.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.22, Shrub_Tree.stats_2023_Density_A.Median, ...
    Shrub_Tree.stats_2023_Density_A.Median - Shrub_Tree.stats_2023_Density_A.IQR_25, ...
    Shrub_Tree.stats_2023_Density_A.IQR_75 - Shrub_Tree.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.3, iqrResults_BD_2022.Tall_Shrub.Median, ...
    iqrResults_BD_2022.Tall_Shrub.Median - iqrResults_BD_2022.Tall_Shrub.IQR_25, ...
    iqrResults_BD_2022.Tall_Shrub.IQR_75 - iqrResults_BD_2022.Tall_Shrub.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(3.32, iqrResults_BD_2023.Shrub_Tree.Median, ...
    iqrResults_BD_2023.Shrub_Tree.Median - iqrResults_BD_2023.Shrub_Tree.IQR_25, ...
    iqrResults_BD_2023.Shrub_Tree.IQR_75 - iqrResults_BD_2023.Shrub_Tree.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

% Plot for Havikpak
errorbar(3.7, Havikpak.stats_2022_Density_D.Median, ...
    Havikpak.stats_2022_Density_D.Median - Havikpak.stats_2022_Density_D.IQR_25, ...
    Havikpak.stats_2022_Density_D.IQR_75 - Havikpak.stats_2022_Density_D.Median, ...
    'x', 'Color', blue_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d = errorbar(3.72, Havikpak.stats_2023_Density_D.Median, ...
    Havikpak.stats_2023_Density_D.Median - Havikpak.stats_2023_Density_D.IQR_25, ...
    Havikpak.stats_2023_Density_D.IQR_75 - Havikpak.stats_2023_Density_D.Median, ...
    'x', 'Color', blue_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.8, Havikpak.stats_2022_Density_A.Median, ...
    Havikpak.stats_2022_Density_A.Median - Havikpak.stats_2022_Density_A.IQR_75, ...
    Havikpak.stats_2022_Density_A.IQR_75 - Havikpak.stats_2022_Density_A.Median, ...
    'x', 'Color', red_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on; 

d1 = errorbar(3.82, Havikpak.stats_2023_Density_A.Median, ...
    Havikpak.stats_2023_Density_A.Median - Havikpak.stats_2023_Density_A.IQR_75, ...
    Havikpak.stats_2023_Density_A.IQR_75 - Havikpak.stats_2023_Density_A.Median, ...
    'x', 'Color', red_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d1.Bar.LineStyle = 'dotted'

hold on; 

errorbar(3.9, iqrResults_BD_2022.Havikpak.Median, ...
    iqrResults_BD_2022.Havikpak.Median - iqrResults_BD_2022.Havikpak.IQR_25, ...
    iqrResults_BD_2022.Havikpak.IQR_75 - iqrResults_BD_2022.Havikpak.Median, ...
    '+', 'Color', gray_2022, 'MarkerSize', 8, 'LineWidth', 2.5);
hold on;

d2 = errorbar(3.92, iqrResults_BD_2023.Havikpak.Median, ...
    iqrResults_BD_2023.Havikpak.Median - iqrResults_BD_2023.Havikpak.IQR_25, ...
    iqrResults_BD_2023.Havikpak.IQR_75 - iqrResults_BD_2023.Havikpak.Median, ...
    '+', 'Color', gray_2023, 'MarkerSize', 8, 'LineWidth', 2.5);

%     d2.Bar.LineStyle = 'dotted'

hold on;

% Add vertical dashed lines
for pos = line_positions
    xline(pos, 'k', 'LineWidth', 1);
end

% Set plot limits and labels
xlim([0 4.2]);
ylim([0 400]); 

xticks([0.3 0.9 1.5 2.1 2.7 3.3 3.9]);
xticklabels({'Upper Plateau','TVC','Valley','Small Shrub','Mixed Shrub','Shrub Tree','Havikpak'});

ylabel('Bulk Density (kg m^-^3)');
xlabel('Site');
hold off;

% legend([h1, h2, h3, h4, h5], {'Default SVS2-Crocus', 'Arctic SVS2-Crocus', 'Magnaprobe', 'Pit', 'SWE Tube'}, 'Position', [0.5, 0.05, 0.1, 0.1]);